sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

before_script:
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - ./vendor/bin/phpunit -c tests/unit/ --coverage-clover=coverage.clover
  - ./vendor/bin/phpunit -c tests/container/

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
